DjangoProject_blindbox/DjangoProject_blindbox/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app01.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoProject_blindbox/app01/urls.py
from django.urls import path

from app01 import views

urlpatterns = [
    path('', views.blindbox_index, name='index'),
    path('blindbox/add/', views.blindbox_add, name='blindbox_add'),
    path('blindbox/list/male/', views.blindbox_list_male, name='blindbox_list_male'),
    path('blindbox/list/female/', views.blindbox_list_female, name='blindbox_list_female'),
    path('blindbox/male/', views.blindbox_male, name='blindbox_male'),
    path('blindbox/female/', views.blindbox_female, name='blindbox_female'),
    path('blindbox/<int:nid>/detail/',views.blindbox_detail,name='blindbox_detail'),
    path('blindbox/placed/myself/',views.blindbox_placed_myself,name='blindbox_placed_myself'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('login/email/', views.login_email, name='login_email'),
    path('logout/', views.logout, name='logout'),
    path('image/code/',views.image_code),
    path('email/code/',views.email_code),
    path('random/chose/', views.blindbox_random_chose, name='blindbox_random_chose'),
    path('chosen/myself/', views.blindbox_chosen_myself, name='blindbox_chosen_myself'),
    path('blindbox/comment/delete/', views.blindbox_comment_delete, name='blindbox_comment_delete'),
    path('comment/', views.comment, name='comment'),
    path('personal/data/', views.personal_data, name='personal_data'),

    path('task/list/', views.task_list, name='task_list'),
    path('task/ajax/', views.task_ajax, name='task_ajax'),
    path('task/ajax1/', views.task_ajax1, name='task_ajax1'),

]

DjangoProject_blindbox/app01/models.py
from datetime import  datetime
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models

class User(models.Model):
    username = models.CharField(verbose_name="用户名",max_length=32,unique=True)
    password = models.CharField(verbose_name="密码",max_length=64)
    email = models.EmailField(blank=True,null=True)
    avatar = models.ImageField(blank=True,null=True,upload_to="avatar/")
    def __str__(self):
        return self.username

class BlindBoxData(models.Model):
    name = models.CharField(verbose_name='姓名',max_length=100)
    age = models.IntegerField(verbose_name='年龄')
    gender_choices = (
        (1, '男'),
        (2, '女'),
    )
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choices)
    email = models.EmailField(verbose_name='邮箱', max_length=100)
    contact = models.CharField(verbose_name='联系方式',max_length=100)
    address = models.CharField(verbose_name='住址',max_length=100)
    introduction = models.CharField(verbose_name='个人简介',max_length=500,blank=True,null=True)
    demand = models.CharField(verbose_name='需求',max_length=500,blank=True,null=True)
    user = models.ForeignKey(verbose_name='用户',to="User",to_field="username",on_delete=models.CASCADE,default='Tobbolc')
    created_at = models.DateTimeField(verbose_name='时间',default=datetime.now)
    def __str__(self):
        return self.name

class Comment(models.Model):
    content = RichTextUploadingField(config_name='default',)
    created_at = models.DateTimeField(auto_now_add=True)
    # user = models.ForeignKey(verbose_name='用户',to="User",to_field="username",on_delete=models.CASCADE,default='Tobbolc')
    # blind_box = models.ForeignKey(verbose_name='评论',to="BlindBoxData",to_field="id",on_delete=models.CASCADE,default=1,unique=True)
    # def __str__(self):
    #     return f'{self.user.username} on {self.created_at}'

class ChosenMyself(models.Model):
    name = models.CharField(verbose_name='姓名', max_length=100)
    age = models.IntegerField(verbose_name='年龄')
    gender_choices = (
        (1, '男'),
        (2, '女'),
    )
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choices, default=1)
    email = models.EmailField(verbose_name='邮箱', max_length=100)
    contact = models.CharField(verbose_name='联系方式', max_length=100)
    address = models.CharField(verbose_name='住址', max_length=100)
    introduction = models.CharField(verbose_name='个人简介', max_length=500, blank=True, null=True)
    demand = models.CharField(verbose_name='需求', max_length=500, blank=True, null=True)
    user = models.ForeignKey(verbose_name='用户', to="User", to_field="username", on_delete=models.CASCADE, default='Tobbolc')
    created_at = models.DateTimeField(verbose_name='时间', default=datetime.now)

class BlindboxComment(models.Model):
    content = models.CharField(verbose_name='评论内容', max_length=500)
    created_at = models.DateTimeField(verbose_name='时间', auto_now_add=True)
    user = models.ForeignKey(verbose_name='用户', to="User", to_field="username", on_delete=models.CASCADE, default='Tobbolc')
    blind_box = models.ForeignKey(verbose_name='评论', to="BlindBoxData", to_field="id", on_delete=models.CASCADE,default=3)

DjangoProject_blindbox/templates/blindbox_add.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新建盲盒</h3>
            </div>
            <div style="margin-inline: 10px" class="panel-body">
                <form method="post" novalidate="novalidate">
                    {% csrf_token %}
                    {% for item in form %}
                        <div class="form-group">
                            <label>{{ item.label }}</label>
                            {{ item }}
                            <span style="color: red">{{ item.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
        $(function () {
            $('#id_created_at').datepicker({
                format: 'yyyy-mm-dd',
                language: 'zh-CN',
                autoclose: true,
                startDate: '+0d',
            })
        })
    </script>
{% endblock %}

DjangoProject_blindbox/templates/blindbox_chosen_myself.html
{% extends 'layout.html' %}

{% block css %}
    <style>
        .card {
            border: 1px solid #ccc; /* 添加外边框 */
            margin-bottom: 20px; /* 卡片之间的间隔 */
            box-shadow: 5px 5px 20px #aaa; /* 添加阴影效果 */
            border-radius: 10px;
        }

        .card-body {
            padding: 15px; /* 增加卡片内部的填充 */
        }

        .card-title {
            font-weight: bold; /* 标题加粗 */
            color: #333; /* 标题颜色 */
        }

        .card-text {
            color: #666; /* 文本颜色 */
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <p>这里是当前用户{{ user }}所抽取的所有盲盒</p>
            <p><a class="btn btn-success btn-lg" style="margin-bottom: 20px" href="/blindbox/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建盲盒
            </a>
                <a class="btn btn-primary btn-lg" style="margin-bottom: 20px" href="/random/chose/">
                    <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
                    抽取盲盒
                </a>
            </p>
        </div>
        <div class="row">
            {% for item in datalist %}
                <div class="col-md-2">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">姓名：{{ item.name }}</h5>
                            <p class="card-text">年龄：{{ item.age }}</p>
                            <p class="card-text">简介：{{ item.introduction }}</p>
                            <p class="card-text">需求：{{ item.demand }}</p>
                            <a href="/blindbox/{{ item.id }}/detail/" class="btn btn-primary btn-xs">详 情</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

DjangoProject_blindbox/templates/blindbox_detail.html
{% extends 'layout.html' %}

{% block css %}
    <style>
        .card {
            border: 1px solid #ccc; /* 添加外边框 */
            margin-bottom: 20px; /* 卡片之间的间隔 */
            box-shadow: 5px 5px 20px #aaa; /* 添加阴影效果 */
            border-radius: 10px;
        }

        .card-body {
            padding: 15px; /* 增加卡片内部的填充 */
        }

        .card-title {
            font-weight: bold; /* 标题加粗 */
            color: #333; /* 标题颜色 */
        }

        .card-text {
            color: #666; /* 文本颜色 */
        }

        .container1 {
            display: flex; /*flexbox布局*/
            justify-content: space-between; /*主轴上两端对齐 */
            flex-wrap: wrap; /*必要时换行*/
        }

    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <h3><span class="glyphicon glyphicon-list-alt" aria-hidden="true">盲盒详情</span></h3>
        <a href="/blindbox/{{ id_up }}/detail/" class="btn btn-primary btn-xs"
           style="width: 80px; height: 30px; margin-bottom: 10px; display:flex; justify-content: center; align-items: center;">上一页</a>
        <div class="row">
            {% for item in row_objects %}
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text">姓名：{{ item.name }}</p>
                            <p class="card-text">年龄：{{ item.age }}</p>
                            <p class="card-text">性别：{{ item.get_gender_display }}</p>
                            <p class="card-text">联系方式：{{ item.contact }}</p>
                            <p class="card-text">邮箱：{{ item.email }}</p>
                            <p class="card-text">住址：{{ item.address }}</p>
                            <p class="card-text">个人简介：{{ item.introduction }}</p>
                            <p class="card-text">择偶需求：{{ item.demand }}</p>
                            <p class="card-text">创建时间：{{ item.created_at }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <a href="/blindbox/{{ id_down }}/detail/" class="btn btn-primary btn-xs"
           style="width: 80px; height: 30px; display:grid; place-items: center">下一页</a>
        <h3><span class="glyphicon glyphicon-comment" aria-hidden="true">评论({{ comment_count }})</span></h3>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <label style="margin-left: 2px">历史评论</label>
                        <div class="container1">
                            {% if datalist %}
                                {% for item in datalist %}
                                    <div class="col-md-6">
                                        <p class="data1">{{ item.content }}</p>
                                    </div>
                                    {% if item.user.username == user_now %}
                                        <div class="col-md-6" style="margin-left: auto">
                                            <p style="margin-left: 100px" class="data2">{{ item.created_at }} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ item.user.username }}<a href="/blindbox/comment/delete/?nid={{ item.id }}" style="margin-left: 50px" class="btn btn-danger btn-xs">删除</a></p>

                                        </div>
                                    {% else %}
                                        <div class="col-md-6" style="margin-left: auto">
                                            <p style="margin-left: 100px" class="data2">{{ item.created_at }} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ item.user.username }}</p>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            {% else %}
                                <p style="margin-left: 2px">暂无评论</p>
                            {% endif %}

                        </div>
                        <form class="form-horizontal" method="post">
                            {% csrf_token %}
                            <div class="form-group" style="margin-left: 3px">
                                <label>内容</label>
                                <input type="text" class="form-control" placeholder="说点什么..." name="content"
                                       style=" max-width: 1095px"/>
                            </div>
                            <button type="submit" class="btn btn-primary">评 论</button>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>


{% endblock %}

DjangoProject_blindbox/templates/blindbox_female.html
{% extends 'layout.html' %}

{% block css %}
    <style>
        .card {
            border: 1px solid #ccc; /* 添加外边框 */
            margin-bottom: 20px; /* 卡片之间的间隔 */
            box-shadow: 5px 5px 20px #aaa; /* 添加阴影效果 */
            border-radius: 10px;
        }

        .card-body {
            padding: 15px; /* 增加卡片内部的填充 */
        }

        .card-title {
            font-weight: bold; /* 标题加粗 */
            color: #333; /* 标题颜色 */
        }

        .card-text {
            color: #666; /* 文本颜色 */
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <p>所有的女生盲盒都在这里了，<s>想要了解详情就点击按钮</s></p>
            <p><a class="btn btn-success btn-lg" style="margin-bottom: 20px" href="/blindbox/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建盲盒
            </a>
                <a class="btn btn-primary btn-lg" style="margin-bottom: 20px" href="/random/chose/">
                    <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
                    抽取盲盒
                </a>
            </p>
        </div>
        <div class="row">
            {% for item in datalist %}
                <div class="col-md-2">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">用户：{{ item.user.username }}</h5>
                            <p class="card-text">姓名：{{ item.name }}</p>
                            <p class="card-text">年龄：{{ item.age }}</p>
                            <p class="card-text">简介：{{ item.introduction }}</p>
                            <a href="/blindbox/{{ item.id }}/detail/" class="btn btn-primary btn-xs">详 情</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="clearfix">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </div>
    </div>
{% endblock %}

DjangoProject_blindbox/templates/blindbox_list_male.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/blindbox/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建盲盒
            </a>
            <a class="btn btn-primary" href="/random/chose/">
                <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
                抽取盲盒
            </a>
        </div>
    </div>
    <div class="container">
        <div class="bs-example" data-example-id="table-within-panel">
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">盲盒列表——男生</div>
                <div class="panel-body">
                    <div style="margin-bottom: 10px">
                        <s>这里是男生盲盒后台，</s>本站目前有{{ data1 }}个男生盲盒,{{ data2 }}个用户
                    </div>
                </div>
                <table class="table">
                    <thead>
                    <tr>
                        <th>用户</th>
                        <th>姓名</th>
                        <th>年龄</th>
                        <th>邮箱</th>
                        <th>联系方式</th>
                        <th>地址</th>
                        <th>个人简介</th>
                        <th>择偶需求</th>
                        <th>提交时间</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for obj in datalist %}
                        <tr>
                            <th scope="row">{{ obj.user.username }}</th>
                            <td>{{ obj.name }}</td>
                            <td>{{ obj.age }}</td>
                            <td>{{ obj.email }}</td>
                            <td>{{ obj.contact }}</td>
                            <td>{{ obj.address }}</td>
                            <td>{{ obj.introduction }}</td>
                            <td>{{ obj.demand }}</td>
                            <td>{{ obj.created_at|date:"Y-m-d H:i:s" }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="clearfix">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript">
        $(function () {
            bindButtonAdd();
        })

        //点击新建按钮，显示对话框
        function bindButtonAdd() {
            $("#btnAdd").click(function () {
                $("#myModal").modal('show');
            });
        }
    </script>
{% endblock %}

DjangoProject_blindbox/templates/blindbox_placed_myself.html
{% extends 'layout.html' %}

{% block css %}
    <style>
        .card {
            border: 1px solid #ccc; /* 添加外边框 */
            margin-bottom: 20px; /* 卡片之间的间隔 */
            box-shadow: 5px 5px 20px #aaa; /* 添加阴影效果 */
            border-radius: 10px;
        }

        .card-body {
            padding: 15px; /* 增加卡片内部的填充 */
        }

        .card-title {
            font-weight: bold; /* 标题加粗 */
            color: #333; /* 标题颜色 */
        }

        .card-text {
            color: #666; /* 文本颜色 */
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <p>这里是当前用户{{ user }}所创建的所有盲盒</p>
            <p><a class="btn btn-success btn-lg" style="margin-bottom: 20px" href="/blindbox/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建盲盒
            </a>
                <a class="btn btn-primary btn-lg" style="margin-bottom: 20px" href="/random/chose/">
                    <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
                    抽取盲盒
                </a>
            </p>
        </div>
        <div class="row">
            {% for item in datalist %}
                <div class="col-md-2">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">用户：{{ item.user.username }}</h5>
                            <p class="card-text">姓名：{{ item.name }}</p>
                            <p class="card-text">年龄：{{ item.age }}</p>
                            <p class="card-text">简介：{{ item.introduction }}</p>
                            <a href="/blindbox/{{ item.id }}/detail/" class="btn btn-primary btn-xs">详 情</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="clearfix">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </div>
    </div>
{% endblock %}

DjangoProject_blindbox/templates/blindbox_random_chose.html
{% extends 'layout.html' %}

{% block css %}
    <style>
        .card {
            border: 1px solid #ccc; /* 添加外边框 */
            margin-bottom: 20px; /* 卡片之间的间隔 */
            box-shadow: 5px 5px 20px #aaa; /* 添加阴影效果 */
            border-radius: 10px;
        }

        .card-body {
            padding: 15px; /* 增加卡片内部的填充 */
        }

        .card-title {
            font-weight: bold; /* 标题加粗 */
            color: #333; /* 标题颜色 */
        }

        .card-text {
            color: #666; /* 文本颜色 */
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
    <p><a class="btn btn-primary btn-lg" style="margin-bottom: 20px" href="/random/chose/">
        <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
        再次抽取
    </a></p>
        <div class="row">
        {% if random_object %}
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">用户：{{ random_object.username }}</h5>
                            <p class="card-text">姓名：{{ random_object.name }}</p>
                            <p class="card-text">年龄：{{ random_object.age }}</p>
                            <p class="card-text">简介：{{ random_object.introduction }}</p>
                            <a href="/blindbox/{{ random_object.id }}/detail/" class="btn btn-primary btn-xs">详 情</a>
                        </div>
                    </div>
                </div>
        {% else %}
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <p>{{ message }}</p>
                    </div>
                </div>
            </div>
        {% endif %}
        </div>
    </div>
{% endblock %}

DjangoProject_blindbox/templates/comment.html
<script src="/static/ckeditor/ckeditor/ckeditor-init.js"></script>
<script src="/static/ckeditor/ckeditor/ckeditor/ckeditor.js"></script>

{% block content %}
    <div class="left">
        <form method="post" action="/">
            {% csrf_token %}
            {{ form.as_p }}
        </form>
        <hr>
        <input style="float:right" type="submit" value="发布！" class="button">
        <button type="button" style="float: right" value="发布" data-mce-placeholder="sss" class="btn-primary"></button>
    </div>
    <div id="comments" class="comment-area">
        <h2><i style="padding-right: 0.3em" class="fa fa-comments"></i>评论</h2>

        <p class="no-comments-message">目前没有评论。</p>


        <div id="new-comment" class="form-area comment-submit">
            <h3>新评论</h3>
            <hr>
            <form class="comment-submit-form" action="" method="post">
                <input type="hidden" name="csrfmiddlewaretoken"
                       value="CjVrPkok3Odw0WK6MMtqVtSRt9Hddc4FDPo12hSRpkZzCipR67Nzh0TuDoCKaQSC"> <input type="hidden"
                                                                                                        name="parent"
                                                                                                        id="id_parent">
                <div class="comment-post-wrapper">
                    <div id="comment-form-body">
                        <div id="id_body-wmd-wrapper" class="wmd-wrapper">
                            <div class="wmd-panel">
                                <div id="id_body_wmd_button_bar">
                                    <ul id="wmd-button-row" class="wmd-button-row">
                                        <li class="wmd-button" id="wmd-bold-button" title="Strong <strong> Ctrl+B"
                                            style="left: 0px;"><span style="background-position: 0px 0px;"></span></li>
                                        <li class="wmd-button" id="wmd-italic-button" title="Emphasis <em> Ctrl+I"
                                            style="left: 25px;"><span style="background-position: -20px 0px;"></span>
                                        </li>
                                        <li class="wmd-spacer wmd-spacer1" id="wmd-spacer1"></li>
                                        <li class="wmd-button" id="wmd-latex-button" title="Latex embed - Ctrl+M"
                                            style="left: 75px;"><span style="background-position: -40px 0px;"></span>
                                        </li>
                                        <li class="wmd-button" id="wmd-latex-button-display"
                                            title="Latex display embed - Ctrl+Space" style="left: 100px;"><span
                                                style="background-position: -60px 0px;"></span></li>
                                        <li class="wmd-spacer wmd-spacer2" id="wmd-spacer2"></li>
                                        <li class="wmd-button" id="wmd-link-button" title="Hyperlink <a> Ctrl+L"
                                            style="left: 150px;"><span style="background-position: -80px 0px;"></span>
                                        </li>
                                        <li class="wmd-button" id="wmd-user-reference-button" title="User reference"
                                            style="left: 175px;"><span style="background-position: -100px 0px;"></span>
                                        </li>
                                        <li class="wmd-button" id="wmd-quote-button"
                                            title="Blockquote <blockquote> Ctrl+Q" style="left: 200px;"><span
                                                style="background-position: -120px 0px;"></span></li>
                                        <li class="wmd-button" id="wmd-code-button"
                                            title="Code Sample <pre><code> Ctrl+K" style="left: 225px;"><span
                                                style="background-position: -140px 0px;"></span></li>
                                        <li class="wmd-button" id="wmd-image-button" title="Image <img> Ctrl+G"
                                            style="left: 250px;"><span style="background-position: -160px 0px;"></span>
                                        </li>
                                        <li class="wmd-spacer wmd-spacer3" id="wmd-spacer3"></li>
                                        <li class="wmd-button" id="wmd-olist-button" title="Numbered List <ol> Ctrl+O"
                                            style="left: 300px;"><span style="background-position: -180px 0px;"></span>
                                        </li>
                                        <li class="wmd-button" id="wmd-ulist-button" title="Bulleted List <ul> Ctrl+U"
                                            style="left: 325px;"><span style="background-position: -200px 0px;"></span>
                                        </li>
                                        <li class="wmd-button" id="wmd-heading-button" title="Heading <h1>/<h2> Ctrl+H"
                                            style="left: 350px;"><span style="background-position: -220px 0px;"></span>
                                        </li>
                                        <li class="wmd-button" id="wmd-hr-button" title="Horizontal Rule <hr> Ctrl+R"
                                            style="left: 375px;"><span style="background-position: -240px 0px;"></span>
                                        </li>
                                        <li class="wmd-spacer wmd-spacer3" id="wmd-spacer3"></li>
                                        <li class="wmd-button" id="wmd-undo-button" title="Undo - Ctrl+Z"
                                            style="left: 425px;"><span
                                                style="background-position: -260px -20px;"></span></li>
                                        <li class="wmd-button" id="wmd-redo-button" title="Redo - Ctrl+Y"
                                            style="left: 450px;"><span
                                                style="background-position: -280px -20px;"></span></li>
                                    </ul>
                                </div>
                                <textarea class=" wmd-input" id="id_body" name="body" required=""></textarea>
                            </div>

                            <div id="id_body-preview" data-preview-url="/haima/widgets/preview/comment"
                                 data-textarea-id="id_body" data-timeout="1000"
                                 class="wmd-panel wmd-preview dmmd-preview dmmd-no-button">
                                <div class="dmmd-preview-update"><i class="fa fa-refresh"></i> 更新预览</div>
                                <div class="dmmd-preview-content content-description"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                <input style="float:right" type="submit" value="发布！" class="button">
            </form>
        </div>
    </div>
{% endblock %}

DjangoProject_blindbox/templates/personal_data.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label>用户名：</label>
    <input type="text" class="form-control" placeholder="标题" name="username"  value="{{ data.username }}" readonly/>
    <label>密码：</label>
    <input type="text" class="form-control" placeholder="标题" name="password"  value="{{ data.password }}" readonly/>
    <label>邮箱：</label>
    <input type="text" class="form-control" placeholder="标题" name="email"  value="{{ data.email }}" readonly/>
    {{ form.as_p }}
    <button type="submit" style="margin-top: 10px; margin-bottom: 10px" class="btn-primary">上 传</button>
    </form>
    <img src="{{ MEDIA_URL }}{{ data.avatar }}" alt="" style="width: 50px; height: 50px; border-radius: 25px">
</div>

{% endblock %}

DjangoProject_blindbox/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>

        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="account">
    <h2>用户注册</h2>
    <form method="post" novalidate="novalidate">
        {% csrf_token %}
        {% for item in form %}
            <div class="form-group">
                <label>{{ item.label }}</label>
                {{ item }}
                <span style="color: red">{{ item.errors }}</span>
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">注 册</button>
        <a href="/login/">已有帐号？</a>
    </form>
</div>
</body>
</html>